server:
  port : 8000
spring:
  application:
    name: ms-api-gateway
  main:
    web-application-type: reactive
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/ui/v1/**]':
            allowedOrigins: "http://localhost:3000"
            exposedHeaders: "page-total-count"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
              - HEAD
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        -   id: ms-user-service
            uri: lb://ms-user-service
            predicates:
              - Path=/ui/v1/user/**, /api/v1/user/**, /api/v1/auth/**
            filters:
              - name: AuthFilter
              - RewritePath=/ui/v1/user(?<segment>/?.*), /ms-user-service/ui/v1/user$\{segment}
              - RewritePath=/api/v1/auth/(?<segment>.*), /ms-user-service/api/v1/auth/$\{segment}
              - RewritePath=/api/v1/user/(?<segment>.*), /ms-user-service/api/v1/user/$\{segment}

        #        Do not apply filter for this route
        -   id: ms-user-service-auth
            uri: lb://ms-user-service
            predicates:
              - Path=/ui/v1/auth/**
            filters:
              - RewritePath=/ui/v1/auth/(?<segment>.*), /ms-user-service/ui/v1/auth/$\{segment}

        -   id: ms-tweet-service
            uri: lb://ms-tweet-service
            predicates:
              - Path=/ui/v1/tweets/**
            filters:
              - name: AuthFilter
              - RewritePath=/ui/v1/tweets(?<segment>/?.*), /ms-tweet-service/ui/v1/tweets$\{segment}

        -   id: ms-image-service
            uri: lb://ms-image-service
            predicates:
              - Path=/api/v1/image/**
            filters:
              - name: AuthFilter
              - RewritePath=/api/v1/image(?<segment>/?.*), /ms-image-service/api/v1/image$\{segment}

        -   id: ms-chat-service
            uri: lb://ms-chat-service
            predicates:
              - Path=/ui/v1/chat/**
            filters:
              - name: AuthFilter
              - RewritePath=/ui/v1/chat(?<segment>/?.*), /ms-chat-service/ui/v1/chat$\{segment}

        -   id: ms-email-service
            uri: lb://ms-email-service
            predicates:
              - Path=/api/v1/email/suggested
            filters:
              - RewritePath=/api/v1/email/suggested/(?<segment>.*), /ms-email-service/api/v1/email/suggested/$\{segment}

        -   id: ms-websocket-service
            uri: lb://ms-websocket-service
            predicates:
              - Path=/websocket/**, /api/v1/websocket/**
            filters:
              - RewritePath=/websocket/(?<segment>.*), /ms-websocket-service/websocket/$\{segment}
              - RewritePath=/api/v1/websocket(?<segment>/?.*), /ms-websocket-service/api/v1/websocket$\{segment}

authUser:
  url:  http://ms-user-service:8081/ms-user-service/api/v1/auth

#  zipkin:
#    base-url: http://${ZIPKIN_HOST:localhost}:9411

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${EUREKA_HOST:localhost}

jwt:
  secret: 208bc47b3e1ee5554e388c735b9f234f89ac246e8ce463c8313fc1cff16e760e
