server:
  port : 8000

management:
  endpoint:
    gateway:
      enabled: true # default value
  web:
    exposure:
      include: gateway
logging:
  level:
    reactor:
      netty: INFO
    org.springframework.web.HttpLogging: TRACE
    org.springframework.web.filter.CorsFilter: DEBUG
    org.springframework.security: DEBUG
    reactor.netty.http.server: TRACE
    reactor.netty.http.client: TRACE
    logging.level.com.netflix.eureka: TRACE
    logging.level.com.netflix.discovery: TRACE
    org:
      springframework:
        cloud:
          gateway: TRACE
spring:
  application:
    name: ms-api-gateway
  main:
    web-application-type: reactive
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      actuator:
        verbose:
          enabled: false
      httpclient:
        ssl:
          useInsecureTrustManager: true
        wiretap: false
      httpserver:
        wiretap: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/ui/v1/**]':
            allowedOrigins:
              - "https://frontend-twitter.onrender.com"
              - "http://localhost:3000"
            exposedHeaders: "page-total-count"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
              - HEAD
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        -   id: ms-user-service
            uri: https://ms-user-service.onrender.com
            predicates:
              - Path=/ui/v1/user/**, /api/v1/user/**, /api/v1/auth/**
            filters:
              - name: AuthFilter
              - RewritePath=/ui/v1/user(?<segment>/?.*), /ms-user-service/ui/v1/user$\{segment}
              - RewritePath=/api/v1/auth/(?<segment>.*), /ms-user-service/api/v1/auth/$\{segment}
              - RewritePath=/api/v1/user/(?<segment>.*), /ms-user-service/api/v1/user/$\{segment}

        #        Do not apply filter for this route
        -   id: ms-user-service-auth
            uri: https://ms-user-service.onrender.com
            predicates:
              - Path=/ui/v1/auth/**
            filters:
              - RewritePath=/ui/v1/auth/(?<segment>.*), /ms-user-service/ui/v1/auth/$\{segment}

        -   id: ms-tweet-service
            uri: https://ms-tweet-service.onrender.com
            predicates:
              - Path=/ui/v1/tweets/**
            filters:
              - name: AuthFilter
              - RewritePath=/ui/v1/tweets(?<segment>/?.*), /ms-tweet-service/ui/v1/tweets$\{segment}

        -   id: ms-image-service
            uri: https://ms-image-service.onrender.com
            predicates:
              - Path=/api/v1/image/**
            filters:
              - name: AuthFilter
              - RewritePath=/api/v1/image(?<segment>/?.*), /ms-image-service/api/v1/image$\{segment}

        -   id: ms-chat-service
            uri: https://ms-chat-service.onrender.com
            predicates:
              - Path=/ui/v1/chat/**
            filters:
              - name: AuthFilter
              - RewritePath=/ui/v1/chat(?<segment>/?.*), /ms-chat-service/ui/v1/chat$\{segment}

        -   id: ms-email-service
            uri: https://ms-email-service.onrender.com
            predicates:
              - Path=/api/v1/email/suggested
            filters:
              - RewritePath=/api/v1/email/suggested/(?<segment>.*), /ms-email-service/api/v1/email/suggested/$\{segment}

        -   id: ms-websocket-service
            uri: https://ms-websocket-service.onrender.com
            predicates:
              - Path=/websocket/**, /api/v1/websocket/**
            filters:
              - RewritePath=/websocket/(?<segment>.*), /ms-websocket-service/websocket/$\{segment}
              - RewritePath=/api/v1/websocket(?<segment>/?.*), /ms-websocket-service/api/v1/websocket$\{segment}

#  zipkin:
#    base-url: http://${ZIPKIN_HOST:localhost}:9411

authUser:
  url: https://ms-user-service.onrender.com/ms-user-service/api/v1/auth

eureka:
  instance:
    hostname: ms-api-gateway.onrender.com  # Public domain name
    nonSecurePort: 443  # Standard HTTPS port
    securePortEnabled: true  # Enable if you're using HTTPS
    preferIpAddress: false  # Use the hostname instead of the IP address
    statusPageUrlPath: /actuator/info  # Default status page path
    healthCheckUrlPath: /actuator/health  # Default health check path
  client:
    service-url:
      defaultZone: https://ms-eureka-server-syh2.onrender.com/eureka
    fetch-registry: true
    register-with-eureka: true
#  instance:
#    hostname: ms-eureka-server-syh2.onrender.com

jwt:
  secret: 208bc47b3e1ee5554e388c735b9f234f89ac246e8ce463c8313fc1cff16e760e
